language: node_js
node_js:
  - 12
services:
  - docker
before_script:
  - cp .env.dist .env
  - cp docker-compose.override.yml.dist docker-compose.override.yml
  - npm install
jobs:
  include:
    - stage: compile
      if: branch = main
      name: "Compile TypeScript and Lint"
      script:
        - npm run docker-build
        - npm run lint
        - npm run units
        - npm run integration
